# Generated by Django 2.1.7 on 2019-04-06 10:36

from django.db import migrations, models
import product_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product_app.models.user_directory_path),
        ),
    ]
