# Generated by Django 2.1.7 on 2019-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20190407_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=100)),
        ),
    ]
