# Generated by Django 2.1.7 on 2019-12-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
        ('order_app', '0004_auto_20191121_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_app.AddressModel'),
        ),
    ]
